package com.example.recipegeneratoraibot2.service;

import com.example.recipegeneratoraibot2.dtos.ChatCompletionRequest;
import com.example.recipegeneratoraibot2.dtos.ChatCompletionResponse;
import com.example.recipegeneratoraibot2.dtos.MyResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import org.springframework.web.server.ResponseStatusException;

import java.net.URI;

@Service
public class OpenAiService {

    private static final Logger logger = LoggerFactory.getLogger(OpenAiService.class);

    @Value("${app.api-key}")
    private String API_KEY;

    @Value("${app.url}")
    private String URL;

    @Value("${app.model}")
    private String MODEL;

    @Value("${app.temperature}")
    private double TEMPERATURE;

    @Value("${app.max_tokens}")
    private int MAX_TOKENS;

    @Value("${app.frequency_penalty}")
    private double FREQUENCY_PENALTY;

    @Value("${app.presence_penalty}")
    private double PRESENCE_PENALTY;

    @Value("${app.top_p}")
    private double TOP_P;

    private final WebClient client;

    public OpenAiService() {
        this.client = WebClient.create();
    }

    // Constructor for testing, allows injecting a mock WebClient
    public OpenAiService(WebClient client) {
        this.client = client;
    }

    /**
     * Generates a recipe based on the ingredients provided by the user.
     *
     * @param ingredients   List of ingredients for the recipe.
     * @param systemMessage Instructional message guiding the AI's response.
     * @return MyResponse containing the recipe generated by the AI.
     */
    public MyResponse generateRecipe(String ingredients, String systemMessage) {
        ChatCompletionRequest requestDto = new ChatCompletionRequest();
        requestDto.setModel(MODEL);
        requestDto.setTemperature(TEMPERATURE);
        requestDto.setMax_tokens(MAX_TOKENS);
        requestDto.setTop_p(TOP_P);
        requestDto.setFrequency_penalty(FREQUENCY_PENALTY);
        requestDto.setPresence_penalty(PRESENCE_PENALTY);
        requestDto.getMessages().add(new ChatCompletionRequest.Message("system", systemMessage));
        requestDto.getMessages().add(new ChatCompletionRequest.Message("user", ingredients));

        try {
            String json = new ObjectMapper().writeValueAsString(requestDto);
            logger.debug("Request JSON: {}", json);

            ChatCompletionResponse response = client.post()
                    .uri(new URI(URL))
                    .header("Authorization", "Bearer " + API_KEY)
                    .contentType(MediaType.APPLICATION_JSON)
                    .accept(MediaType.APPLICATION_JSON)
                    .body(BodyInserters.fromValue(json))
                    .retrieve()
                    .bodyToMono(ChatCompletionResponse.class)
                    .block();

            String responseMsg = response.getChoices().get(0).getMessage().getContent();
            int tokensUsed = response.getUsage().getTotal_tokens();

            logger.info("Tokens used: {}", tokensUsed);
            logger.info("Cost ($0.0015 / 1K tokens): ${}", String.format("%6f", (tokensUsed * 0.0015 / 1000)));

            return new MyResponse(responseMsg);
        } catch (WebClientResponseException e) {
            logger.error("Error response status code: {}", e.getRawStatusCode());
            logger.error("Error response body: {}", e.getResponseBodyAsString());
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "Failed to communicate with the external service.");
        } catch (Exception e) {
            logger.error("Exception", e);
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "An error occurred. Please try again later.");
        }
    }
}
